### ISSUE TITLE
role tracker problems

### ISSUE THREAD

**Issue by tyanas** [basisjs/basisjs#122]
1) role tracker tracks events with undefined data. Parentheses are missed.

2) second event (and all events after it), that matches selector with `*`, is tracked with wrong params if corresponding objects in the tracking map is a nested object:
```
    'user(*)': {
        click: {
            customTracking: {
                id: 'Select user',
                params: {
                    userId: '*'
                }
            }
        }
    }
```

Sometimes object deep copy is needed, because for cases with `*` data from tracking map is transformed with `setDeep`. And it changes source object (item in `selectorList`) when item values are objects too.

**Comment by lahmatiy** [comment]
What reasons?
