### ISSUE TITLE
Wrong warning on route handler removal in basis.router

### ISSUE THREAD

**Issue by sm0g** [basisjs/basisjs#151]
It seems there is a bug in a router's "remove" method. Despite a callback has been found and successfully removed warning message is shown in console: "basis.router: no callback removed". Inside router object "break" statement (line 483) should be replaced with "return".

**Comment by lahmatiy** [comment]
Yep, you're right. PR maybe?

**Comment by istrel** [comment]
This issue is going to be fixed in #150

**Comment by lahmatiy** [comment]
Fixed in [1.10.2](https://github.com/basisjs/basisjs/releases/tag/v1.10.2)
Thanks for the issue!

**Comment by sm0g** [comment]
So fast! Next time I'll provide PR without an issue.
