### ISSUE TITLE
Эксперимент: автоматический биндинг стилей на шаблоны относительно данных/переменных (независимость стилей от шаблона)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [basisjs/basisjs#169]
Приветствую. Сначала хочу поблагодарить за такой крутой фреймворк. Я очень жалею что нашёл его только сейчас. К сожалению хорошие вещи плохо распиарены.
Имею практически точно такие же взгляды, но гораздо меньше опыта и програмерских навыков, это как спасение для меня. Но есть одна вещь.

Возможно ли (я пока только разбираюсь и глубоко ещё не лез, но не могу не удержаться спросить сейчас, думаю этого всё равно нету) у вас биндить стили на переменные шаблона чтобы селекторы автоматически генерировались? А если нет, то есть какие-нибудь простые пути как это можно добиться в вашем фреймворке?
У меня как-то встала потребность менять шаблоны, при этом не модифицируя и не прописывая в шаблонах лишние классы. Решил делить стили на те которые определяют именно стиль (оформление — цвета, вид шрифта и т. п.) и те что определяют только разметку (дизайн/расположение). На самом деле делений ещё больше но для сути сойдёт и это.
И пришёл к тому что вместо того чтобы завязываться на структуру шаблона или классы, можно завязываться на данные и ключевые переменные шаблона.
Поясню подробнее.
Есть к примеру данные:
```JSON
{
	"id": 1,
	"time": "2015-09-23T09:20:00Z",
	"content": "Привет",
	"istopic": 1,
	"img": "/img/05/ed/05ed4699f7504e01835828e32967ddad.png"
}
```
есть шаблон:
```XHTML
<template>
	<msg>
		<sub>
			<a href="#{id}">&gt;&gt;{id}</a>
			<a title="{l10n:current}" href="{v1_url}/{id}"></a>
			<a title="{l10n:parent}" href="{parent}" class="fa fa-code-fork"></a>
			<a title="{l10n:download}" href="{download}" class="fa fa-download"></a>
		</sub>
		<sup>
			<time datetime="{time}"></time><i class="fa fa-clock-o"></i>
		</sup><br />
		<a href="{img}"><img src="{img}" /></a>
		<section>{content}</section>
	</msg>
</template>
```
плюс ещё какая-то логика в скрипте определяющая остальные ключевые переменные.
И тут вместо того чтоб типично описать стили, можно просто завязаться на непосредственно переменные:
```XHTML
<style>
	id {
		color: {primary};
	}
	id[href$="{id}"] {
		color: {secondary};
	}
	time {
		color: {time};
	}
</style>
```
Дальше это само собой генерируется в нормальные селекторы (всякое сложное можно генерировать в уникальный класс который подставится у нужного места шаблона).
Короче сами переменные уже указывают на конструкции и почему бы на них не ссылаться упрощая разработку?
Идея ещё сыровата (нужно допродумать дизайн описания стилей), но суть думаю ясна.
Своего рода по-настоящему семантические стили.
А вы что думаете?

**Comment by smelukov** [comment]
Привет. Да, фреймворк действительно классный, и сейчас мы пытаемся уделять ему больше времени и дулать другие крутые штуки.
По поводу самого вопроса: сейчас есть такая возможность:
<div style="color: {primary}>...</div>
То есть динамически менять стили отталкиваясь от элемента, а не от селектора.
Идея с селекторами кажется интересной. Как минимум можно будет не в вписывать стили в атрибут style
@lahmatiy что скажешь?

**Comment by 0x4E69676874466F78** [comment]
@smelukov, спасибо за ответ, а что за другие крутые штуки?
Ну в итоге style-узел может быть не один, можно по-разному разбить.

**Comment by lahmatiy** [comment]
@0x4E69676874466F78 Не до конца понял какая проблема решается. Зачем нужно трансформировать селекторы?

В шаблонах есть инструкция [`<b:isolate>`](https://github.com/basisjs/articles/blob/master/ru-RU/template/b-isolate.md), которая включает изоляцию стилей (делает имена классов уникальными в разметке и ассоциированных стилях). Если нужно менять вид элемента в зависимости от каких то условий, то необходимые значения прокидываются в шаблон через биндинги, а в шаблоне используются классы модификаторы.
```html
<div class="example example_{foo} example_{bar}">...
```
Так же можно использовать [`<b:define>`](https://github.com/basisjs/articles/blob/master/ru-RU/template/b-define.md) для фиксации возможных значений биндинга в классах.

Возможно это поможет решить ваши задачи.

**Comment by 0x4E69676874466F78** [comment]
Я сначала ещё попробую пописать на базисе компоненты с изоляцией стилей, может переосмыслю ещё всё это. 
Выше просто рассматривайте это как пищу для размышлений, может на что-то натолкнёт. Для меня это своего рода исследование/research.

**Comment by 0x4E69676874466F78** [comment]
Смотрю слайды «DOM-шаблонизаторы – не только "быстро"»
И там:
![48 страница](https://image.slidesharecdn.com/moscowjs-dom-templates-140522104157-phpapp02/95/dom-48-638.jpg)
Вот моя тема про это же только для стилей. Можно так сделать?

**Comment by lahmatiy** [comment]
Спасибо за развернутый ответ.

Предложенный вариант с расширением синтаксиса CSS похож на некий препроцессинг. Подобных решений не мало, придумывать новый не совсем резонно. Новый синтаксис нужно изучать, разбираться в нем, не говоря про реализацию и поддержку (изменение CSS только изначально кажется хорошей идеей, поверьте мне, человеку, который посвятил не мало времени его разбору; чтобы грамотно расширять CSS нужно его хорошо понимать, даже я до сих не могу утверждать, что полностью его понимаю). Это так же очень не просто "продать". По этой причине в basis минимальное кол-во кастомных форматов, по сути только в шаблонах.
Если посмотреть проблему с технической стороны, то тут есть ряд проблем. Во-первых, нужно делать препроцессинг. Это можно делать в рантайме, но это значит, что в приложении будет немалый код, выполняющий эту задачу. Можно делать средствами сборщика, но в этом случае нужен обязательный этап сборки, что замедляет разработку. Остается открытым вопрос отладки и профилирования. Философия basis состоит в том, что все может быть сделано в рантайм, а сборка необязательный этап для разработки. Таким образом достигается гибкость и скорость разработки. Сборка - финальный шаг перед выкладкой в прод. Не хочется уходить от этого. Тем не менее можно добавить "серверный" препроцессинг в разработке, для этого определенным образом настраивается дев-сервер - так можно использовать препроцессоры и прочее. Но это opt-in, на усмотрение проекта.
Во-вторых, нужно вспомнить про механику шаблонов и что делает их быстрыми. Basis формирует эталонный DOM фрагмент, который после клонирует - это очень быстро. Используемый CSS вставляется в документ единожды (при включенной изоляции он предварительно обрабатывается очень простым [трансформером](https://github.com/basisjs/basisjs/blob/master/src/basis/template/isolateCss.js)). Все строится на переиспользовании общего для шаблонов. Если мы говорим про динамические стили для каждого инстанса, то тут придется делать не мало для каждого экземпляра и преимущество переиспользования теряется, получится очень не быстро. JSS делают некоторую магию чтобы решить задачу, но на мой взгляд это костыли. В целом подход JSS может дать некоторое удобство в краткосрочной перспективе, но в долгосрочной (на что в основном ориентируется basis) подход создает много проблем.
Еще стоит отметить, что работа с шаблонами несколько отличается в рантайме и в сборке. В рантайме basis хранит множество отладочной информации о шаблоне и всем с ним связанным (используют инструменты) и все рассчитано больше на замену и обновление описания (live update). В сборке шаблоны сохраняются без отладочной информации, в наиболее компактном виде, а весь CSS объединяется в один файл.

Конечно, в качестве эксперимента можно реализовать описанное выше, если есть большое желание. Все что связанно с шаблонизацией можно найти в папке [src/basis/template](https://github.com/basisjs/basisjs/tree/master/src/basis/template), в сборщике тоже есть код для обработки шаблонов (но до этого нужно еще дойти). Тут стоит понимать, что придется учитывать множество моментов и решить ряд непростых задач. Не уверен, что это резонное приложение усилий.
Может посмотреть на проблему под другим углом? ;)

**Comment by 0x4E69676874466F78** [comment]
> <p>Подобных решений не мало, придумывать новый не совсем резонно
Какие есть не ломающие синтаксис css?
> <p>Это так же очень не просто "продать".
Ну про это я сразу сказал что это эксперимент и "маргинальщина".
Ну а в целом примерно понятно, спасибо за ответ.

**Comment by lahmatiy** [comment]
> Какие есть не ломающие синтаксис css и не смешивающих его с js?

Имелось ввиду CSS пре-/пост-процессоры. В статичной обработке есть less/sass/stylus и другие. Если говорить про рантайм, то это в сторону JSS.
Там проблема в том, что собрать строку в целом понятная история (любой *-процессор делает это) - только тут еще нужно это делать для каждого инстанса (фрагментов CSS будет очень много). И в динамике менять тоже накладно, так как либо нужно целиком заменять старый "фрагмент" CSS, либо как-то очень хитро патчить CSSOM. Есть еще вариант транслировать все в inline стили, но в таком случае задача не проще - нужно как-то разруливать историю с псевдо-классами и штуками вроде `@media`, определять дельту изменений и все это применять. В общем там на каждом шагу какие-то сложности. Формат описания динамических стилей не самая большая проблема.

**Comment by 0x4E69676874466F78** [comment]
Ясно, ну я пока решил в случае с css ограничиться PostCSS для сложных случаев, а потом уже когда наберусь побольше опыта попробовать своё решение сделать.
