### ISSUE TITLE
Статус проекта

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [basisjs/basisjs#184]
Фреймворк совсем заброшен или есть смысл писать багрепорты?

**Comment by lahmatiy** [comment]
Да, сейчас активного развития нет, но возможно к этому еще вернемся. Писать багрепорты смысл определенный есть, особенно если используете.

**Comment by 0x4E69676874466F78** [comment]
Спасибо за ответ, радует. Пытаюсь использовать, но баги и некоторые непонятности досаждают.
Хорошо, тогда чуть позже создам несколько багрепортов.
