### ISSUE TITLE
undefined-значение в шаблоне успевает показать ошибку, если биндингов больше одного

### ISSUE THREAD

**Issue by tyanas** [basisjs/basisjs#25]
Пример, когда ошибка видна:

шаблон
```html
<svg:svg viewBox="0 0 {width} {height}"/>
```
width и height -- js константы

окажется в промежуточном состоянии
```html
<svg:svg viewBox="0 0 undefined 300"/>
```

И про это будет жалоба в консоли
`Invalid value for <svg:svg> attribute viewBox="0 0 undefined 300"`

Но в итоге шаблон окажется в норм состоянии типа
```html
<svg:svg viewBox="0 0 500 300"/>
```

**Comment by lahmatiy** [comment]
Fixed by cbfdf4cb16d230d0514f33c2e2f3cfb3f70c87a2
