### ISSUE TITLE
Планируется ли поддержка typescript?

### ISSUE THREAD

**Issue by cevek** [basisjs/basisjs#26]
Есть ли у вас подготовка под нативные классы?
```javascript
class ModelA extends basis.BaseModel{
   getItems(){}
   constructor(){super()}
}
```

также интересен момент по поводу сетеров гетеров моделей
```javascript
var model1 = new Model();
model1.get("field1");
model1.set("field1");
```
такой код абсолютно невозможно рефакторить

**Comment by lahmatiy** [comment]
Пока не задавались вопросом поддержки TypeScript.
Не совсем понятно что подразумевается под "нативные классы". Это про классы TypeScript или ES6? Про TypeScript не скажу, а насчет ES6 такая ситуация: сейчас у классов максимально минимальный дизайн. Это означает, что при наследовании можно расширять/дополнять только методы. Я сильно не тестировал, но в этой части вроде все работает, как должно. Но при создании классов часто нужно переопределять свойства, и тут ES6 предлагает не совсем удобные решения (в TypeScript насколько знаю с этим проще). У некоторых свойств еще есть [авторасширение](https://github.com/basisjs/articles/blob/master/ru-RU/basis.Class.md#%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5), вот это не будет работать без дополнительных доработок (были мысли как можно было бы сделать, но пока до этого не дошло).

Если говорить про модели, то гетеров нет (читаем из объекта напрямую). Есть "сетеры", но все зависит от [интерфейса](https://github.com/basisjs/articles/blob/master/ru-RU/basis.data.Object.md#%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8). Обычно все данные хранятся в свойстве data и меняются через метод update.
