### ISSUE TITLE
Broken basis.ui.scroller.ScrollPanel#fixPosition

### ISSUE THREAD

**Issue by fateevv** [basisjs/basisjs#71]
In this commit https://github.com/basisjs/basisjs/pull/59/commits/1affe4e5419b33ac974d1fcb859913d6802c9e9a condition become more strict and requires true-like `ScrollPanel#minPositionX` but it equals zero after `ScrollPanel#init` and never will be changed. Some effect of this bug you can see on demo page https://img.w1.ru/2gz6rz. It seems we should exclude `minPositionX` from condition statement.

**Comment by naorunaoru** [comment]
my bad. 
fixed in #98.

**Comment by lahmatiy** [comment]
@fateevv is it ok now?

**Comment by fateevv** [comment]
Yes, scroller works again.
